////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////

namespace Server.Items
{
    public class hex_libraryStairsAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1955, 1, -3, 30}, {52, 2, -4, 3}, {65, 2, -3, 25}// 1	2	3	
			, {1955, 2, -3, 30}, {51, 2, -3, 3}, {52, 2, -4, 5}// 4	5	6	
			, {1314, 2, -3, 35}, {1314, 1, -3, 35}, {52, 1, -4, 25}// 7	8	9	
			, {52, 2, -4, 25}, {66, 1, -4, 40}, {66, 2, -4, 40}// 10	11	12	
			, {67, 2, -3, 23}, {66, 1, -4, 0}, {1958, 1, -1, 40}// 13	14	15	
			, {51, 1, -2, 10}, {1955, 1, 0, 40}, {51, 1, 3, 30}// 16	17	18	
			, {51, 1, 1, 10}, {51, 1, 3, 10}, {51, 1, 0, 10}// 19	20	21	
			, {51, 1, 2, 10}, {61, 1, 1, 30}, {65, 1, -1, 30}// 22	23	24	
			, {1958, 1, -2, 35}, {1955, 1, -1, 35}, {1958, 1, 0, 45}// 25	26	27	
			, {51, 1, -1, 10}, {61, 1, 0, 30}, {1955, 1, -2, 30}// 28	29	30	
			, {1955, 2, -2, 25}, {61, 2, -1, 5}, {1956, 2, -2, 30}// 31	32	33	
			, {51, 0, 0, 30}, {61, 2, -2, 5}, {1956, 2, -1, 25}// 34	35	36	
			, {61, 2, -2, 15}, {65, 1, 1, 40}, {1955, 1, 1, 45}// 37	38	39	
			, {1955, 2, -1, 20}, {65, 2, -1, 15}, {1955, 1, 2, 50}// 40	41	42	
			, {1955, 0, 2, 50}, {1314, 1, 2, 55}, {65, 1, 3, 50}// 43	44	45	
			, {1958, 1, 1, 50}, {1314, 0, 3, 55}, {1955, -1, 2, 50}// 46	47	48	
			, {1314, -2, 2, 55}, {1314, -2, 3, 55}, {1314, -1, 3, 55}// 49	50	51	
			, {1955, -2, 2, 50}, {1314, 2, 3, 15}, {1958, -2, 1, 50}// 52	53	54	
			, {1958, -1, 1, 50}, {1314, 2, 2, 15}, {1314, 1, 3, 55}// 55	56	57	
			, {61, 2, 0, 5}, {1955, 2, 0, 15}, {1956, 2, 0, 20}// 58	59	60	
			, {1955, 2, 1, 10}, {1955, 2, 2, 10}, {1956, 2, 1, 15}// 61	62	63	
			, {65, 2, 1, 7}, {83, -3, 3, 58}, {1958, 0, 1, 50}// 64	65	66	
			, {83, -2, 3, 52}, {1314, 0, 2, 55}, {1314, -1, 2, 55}// 67	68	69	
			, {83, -1, 3, 50}, {83, -1, 3, 52}, {83, 0, 3, 52}// 70	71	72	
			, {66, -4, 3, 52}, {66, -1, 3, 55}, {66, 0, 3, 55}// 73	74	75	
			, {66, 2, 3, 10}, {66, -2, 3, 55}, {2240, 2, 2, 54}// 76	77	78	
			, {2237, 2, 2, 55}, {65, 1, 3, 55}, {83, -3, 3, 52}// 79	80	81	
			, {83, -3, 3, 54}, {83, -3, 3, 56}, {65, 2, 3, 5}// 82	83	84	
			, {65, 2, 3, 3}, {66, 2, 3, 15}, {1959, -3, 2, 50}// 85	86	87	
			, {1960, -3, 1, 50}, {53, 0, -2, 32}, {2239, 3, -3, 36}// 88	89	91	
			, {1958, 3, -3, 0}, {1962, 4, -3, 0}, {1955, 3, 2, 5}// 92	93	94	
			, {1958, 3, 2, 10}, {1955, 3, 3, 10}, {1958, 3, 1, 5}// 95	96	97	
			, {1955, 3, 1, 0}, {1314, 3, 3, 15}, {61, 3, 3, 0}// 98	99	100	
			, {65, 3, 2, 0}, {2238, 3, 4, 15}, {1955, 3, -2, 0}// 101	102	103	
			, {1955, 3, -1, 0}, {1955, 3, 0, 0}, {1955, 3, 1, 0}// 104	105	106	
			, {1957, 4, 0, 0}, {1957, 4, -1, 0}, {1957, 4, -2, 0}// 107	108	109	
			, {1313, 3, 0, 5}, {1313, 3, -1, 5}, {1313, 3, -2, 5}// 110	111	112	
			, {1961, 4, 1, 0}// 113	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new hex_libraryStairsAddonDeed();
			}
		}

		[ Constructable ]
		public hex_libraryStairsAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 60, 1, 2, 30, 0, 0, "", 1);// 90

		}

		public hex_libraryStairsAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class hex_libraryStairsAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new hex_libraryStairsAddon();
			}
		}

		[Constructable]
		public hex_libraryStairsAddonDeed()
		{
			Name = "hex_libraryStairs";
		}

		public hex_libraryStairsAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}