////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////

namespace Server.Items
{
    public class TvTArenaLobbyAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {54, -7, -10, 0}, {53, -7, -9, 0}, {53, -7, -8, 0}// 1	2	3	
			, {53, -7, -7, 0}, {54, -7, 8, 0}, {53, -7, 10, 0}// 4	5	6	
			, {53, -7, 11, 0}, {53, -7, 9, 0}, {52, -5, -10, 0}// 7	8	10	
			, {1173, 6, -9, 0}, {52, -6, -10, 0}, {52, -6, -7, 0}// 11	13	14	
			, {53, 7, -5, 0}, {53, 7, -6, 0}, {53, 7, -7, 0}// 15	16	17	
			, {53, 7, -1, 0}, {53, -5, -9, 0}, {52, -4, -10, 0}// 18	20	21	
			, {52, -2, -10, 0}, {52, -3, -10, 0}, {52, 0, -10, 0}// 22	23	24	
			, {52, -1, -10, 0}, {52, 1, -10, 0}, {52, 2, -10, 0}// 25	26	27	
			, {52, -5, -7, 0}, {1173, 1, -1, 0}, {1173, 0, -3, 0}// 29	32	34	
			, {1173, 2, -8, 0}, {1173, 3, -1, 0}, {1173, 4, -8, 0}// 35	36	37	
			, {1173, 3, -5, 0}, {1173, 3, -4, 0}, {1173, -6, -9, 0}// 38	39	40	
			, {1173, -5, -9, 0}, {1173, 1, -6, 0}, {1173, 1, -4, 0}// 41	43	44	
			, {1173, 1, -3, 0}, {1173, 0, -5, 0}, {53, 7, 1, 0}// 46	49	50	
			, {53, 7, 0, 0}, {1173, -6, -8, 0}, {1173, 6, -1, 0}// 51	52	53	
			, {1173, 6, -2, 0}, {1173, 7, -8, 0}, {1173, 7, -6, 0}// 54	55	56	
			, {1173, 7, -9, 0}, {1173, 6, -3, 0}, {1173, 3, -6, 0}// 58	60	61	
			, {1173, 3, -3, 0}, {1173, 6, 1, 0}, {1173, 6, 0, 0}// 63	66	67	
			, {1173, 4, -1, 0}, {1173, 5, -8, 0}, {1173, 5, -7, 0}// 75	76	78	
			, {1173, -2, -1, 0}, {1173, -1, -8, 0}, {1173, -1, -6, 0}// 85	88	89	
			, {1173, -1, -4, 0}, {1173, -1, -5, 0}, {1173, 5, -4, 0}// 90	91	98	
			, {1173, 5, -6, 0}, {1173, 5, -5, 0}, {1173, 7, -5, 0}// 99	100	101	
			, {1173, 7, -4, 0}, {1173, 7, -3, 0}, {1173, 7, -2, 0}// 102	103	104	
			, {1173, 7, -1, 0}, {1173, -5, -8, 0}, {1173, 5, -1, 0}// 105	106	107	
			, {1173, 5, -2, 0}, {1173, 5, -3, 0}, {1173, 7, -7, 0}// 108	109	110	
			, {1173, 6, -7, 0}, {1173, 6, -8, 0}, {1173, 6, -5, 0}// 111	112	113	
			, {1173, 6, -6, 0}, {1173, 6, -4, 0}, {1173, 7, 0, 0}// 114	115	126	
			, {1173, 7, 1, 0}, {1173, -3, -8, 0}, {1173, -3, -6, 0}// 127	130	131	
			, {1173, -3, -7, 0}, {1173, -3, -5, 0}, {1173, -3, -4, 0}// 132	133	134	
			, {1173, -3, -3, 0}, {1173, -3, -2, 0}, {1173, -3, -1, 0}// 135	136	137	
			, {1173, -2, -8, 0}, {1173, 2, -5, 0}, {1173, 2, -3, 0}// 139	146	148	
			, {1173, 2, -1, 0}, {1173, 3, -8, 0}, {1173, 0, -1, 0}// 149	152	153	
			, {1173, 1, -8, 0}, {1173, -1, -3, 0}, {1173, -1, -1, 0}// 156	158	160	
			, {1173, 0, -8, 0}, {1173, 0, -6, 0}, {1173, 2, -6, 0}// 161	164	171	
			, {1173, -5, -7, 0}, {1173, -6, -7, 0}, {53, 7, -9, 0}// 172	173	174	
			, {53, -5, -7, 0}, {52, 3, -10, 0}, {52, 4, -10, 0}// 175	176	177	
			, {52, 5, -10, 0}, {52, 6, -10, 0}, {52, 7, -10, 0}// 178	179	180	
			, {53, -5, -6, 0}, {53, -5, -5, 0}, {53, -5, -4, 0}// 181	182	183	
			, {53, -5, -3, 0}, {53, -5, -2, 0}, {53, -5, -1, 0}// 184	185	186	
			, {53, -5, 0, 0}, {53, -5, 1, 0}, {53, 7, -2, 0}// 187	188	189	
			, {53, 7, -3, 0}, {53, 7, -4, 0}, {53, 7, -8, 0}// 190	191	192	
			, {52, -6, 11, 0}, {52, -4, 11, 0}, {1173, -3, 4, 0}// 193	196	198	
			, {1173, 5, 7, 0}, {1173, -3, 5, 0}, {1173, -3, 3, 0}// 199	201	202	
			, {1173, -3, 2, 0}, {1173, -3, 6, 0}, {1173, -3, 7, 0}// 203	204	205	
			, {1173, 5, 4, 0}, {1173, 5, 11, 0}, {1173, -4, 11, 0}// 206	207	210	
			, {1173, -4, 10, 0}, {1173, 3, 2, 0}, {1173, 4, 2, 0}// 211	212	213	
			, {51, 7, 11, 0}, {1173, 1, 2, 0}, {1173, 5, 5, 0}// 215	218	220	
			, {1173, 4, 9, 0}, {1173, 3, 4, 0}, {53, 7, 8, 0}// 221	222	223	
			, {53, 7, 7, 0}, {53, 7, 6, 0}, {53, 7, 4, 0}// 224	225	226	
			, {53, 7, 5, 0}, {53, 7, 3, 0}, {53, 7, 2, 0}// 227	228	229	
			, {1173, 2, 11, 0}, {1173, 2, 10, 0}, {1173, 5, 8, 0}// 237	238	239	
			, {1173, 5, 6, 0}, {1173, -5, 11, 0}, {1173, 1, 4, 0}// 240	242	243	
			, {1173, 2, 9, 0}, {1173, 4, 11, 0}, {1173, 5, 3, 0}// 244	245	246	
			, {1173, 5, 2, 0}, {1173, -5, 10, 0}, {1173, 5, 10, 0}// 247	248	249	
			, {1173, 5, 9, 0}, {1173, 3, 5, 0}, {1173, 3, 7, 0}// 250	252	253	
			, {1173, 3, 6, 0}, {1173, 3, 9, 0}, {1173, 2, 7, 0}// 254	256	258	
			, {1173, 2, 6, 0}, {1173, 2, 4, 0}, {1173, 2, 2, 0}// 260	261	263	
			, {1173, 1, 11, 0}, {1173, 1, 10, 0}, {1173, 1, 9, 0}// 264	265	266	
			, {1173, 3, 11, 0}, {1173, 3, 10, 0}, {1173, 3, 9, 0}// 267	268	269	
			, {1173, 3, 10, 0}, {1173, 3, 11, 0}, {1173, 4, 2, 0}// 270	271	272	
			, {1173, -2, 10, 0}, {1173, -2, 11, 0}, {1173, -1, 2, 0}// 277	278	279	
			, {1173, -1, 4, 0}, {1173, -1, 5, 0}, {1173, -1, 6, 0}// 280	282	283	
			, {1173, -1, 7, 0}, {1173, -1, 9, 0}, {1173, -1, 10, 0}// 284	285	287	
			, {1173, -1, 11, 0}, {1173, 0, 2, 0}, {1173, 0, 4, 0}// 288	289	290	
			, {1173, 1, 9, 0}, {1173, 1, 10, 0}, {1173, 1, 11, 0}// 297	298	299	
			, {1173, -6, 11, 0}, {1173, -6, 10, 0}, {1173, -3, 7, 0}// 300	301	302	
			, {1173, -3, 8, 0}, {1173, -3, 9, 0}, {1173, -3, 11, 0}// 303	304	305	
			, {1173, -3, 10, 0}, {1173, -2, 2, 0}, {1173, 3, 2, 0}// 306	308	309	
			, {1173, -3, 2, 0}, {1173, 4, 11, 0}, {1173, -3, 3, 0}// 316	317	318	
			, {1173, -3, 4, 0}, {51, -5, 8, 0}, {1173, -3, 5, 0}// 319	323	324	
			, {1173, -3, 6, 0}, {1173, -4, 10, 0}, {1173, -4, 11, 0}// 325	332	333	
			, {1173, -2, 9, 0}, {1173, 1, 5, 0}, {1173, 1, 7, 0}// 334	336	338	
			, {52, 1, 11, 0}, {52, 2, 11, 0}, {52, 3, 11, 0}// 345	346	347	
			, {52, 4, 11, 0}, {52, 5, 11, 0}, {52, 6, 11, 0}// 348	349	350	
			, {51, -5, 11, 0}, {1173, -2, 9, 0}, {1173, -2, 10, 0}// 351	355	357	
			, {1173, -2, 11, 0}, {1173, 0, 6, 0}, {1173, 0, 7, 0}// 358	359	360	
			, {1173, 0, 10, 0}, {1173, 0, 9, 0}, {1173, 0, 11, 0}// 362	363	364	
			, {53, 7, 9, 0}, {53, 7, 10, 0}, {1173, -3, 8, 0}// 365	366	367	
			, {1173, -3, 10, 0}, {1173, -3, 9, 0}, {1173, 4, 10, 0}// 368	369	370	
			, {1173, 6, 2, 0}, {1173, 6, 3, 0}, {1173, 6, 4, 0}// 371	372	373	
			, {1173, 6, 5, 0}, {1173, 6, 6, 0}, {1173, 6, 8, 0}// 374	375	376	
			, {1173, 6, 7, 0}, {1173, 6, 9, 0}, {1173, 6, 10, 0}// 377	378	379	
			, {1173, 6, 11, 0}, {1173, 7, 2, 0}, {1173, 7, 3, 0}// 380	381	382	
			, {1173, 7, 4, 0}, {1173, 7, 6, 0}, {1173, 7, 5, 0}// 383	384	385	
			, {1173, 7, 7, 0}, {1173, 7, 8, 0}, {1173, 7, 9, 0}// 386	387	388	
			, {1173, 7, 10, 0}, {1173, 7, 11, 0}, {1173, 0, 10, 0}// 389	390	394	
			, {1173, 0, 9, 0}, {1173, 0, 11, 0}, {1173, 1, 2, 0}// 395	396	397	
			, {1173, -1, 2, 0}, {1173, -1, 9, 0}, {1173, -1, 11, 0}// 401	405	406	
			, {1173, -1, 10, 0}, {1173, 0, 2, 0}, {1173, -3, 11, 0}// 407	408	409	
			, {1173, -2, 2, 0}, {1173, 2, 9, 0}, {1173, 2, 10, 0}// 410	414	416	
			, {1173, 2, 11, 0}, {1173, 4, 9, 0}, {1173, 4, 10, 0}// 417	423	424	
			, {1173, 2, 2, 0}, {1173, -6, 9, 0}, {52, 0, 11, 0}// 425	426	428	
			, {52, -1, 11, 0}, {52, -3, 11, 0}, {52, -2, 11, 0}// 429	430	431	
			, {1173, -5, 9, 0}, {52, -6, 8, 0}, {53, -5, 2, 0}// 432	433	434	
			, {53, -5, 3, 0}, {53, -5, 4, 0}, {53, -5, 5, 0}// 435	436	437	
			, {53, -5, 6, 0}, {53, -5, 7, 0}, {53, -5, 10, 0}// 438	439	440	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TvTArenaLobbyAddonDeed();
			}
		}

		[ Constructable ]
		public TvTArenaLobbyAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1173, -3, 1, 0, 1000, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1173, -4, 1, 0, 1000, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1173, 4, 0, 0, 1000, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1173, -4, -2, 0, 1000, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1173, 3, -7, 0, 35, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1173, 0, -4, 0, 35, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1173, 2, -9, 0, 1000, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1173, 4, 1, 0, 1000, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1173, 1, -5, 0, 35, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 1173, 1, -2, 0, 35, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 1173, 2, -7, 0, 35, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 1173, 3, 1, 0, 1000, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1173, 3, -2, 0, 35, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1173, 4, -9, 0, 1000, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1173, -4, -3, 0, 1000, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1173, 3, 0, 0, 1000, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1173, 5, 1, 0, 1000, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1173, 4, -7, 0, 35, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1173, 4, -6, 0, 35, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1173, 4, -5, 0, 35, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1173, 4, -4, 0, 35, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1173, 4, -3, 0, 35, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 1173, 4, -2, 0, 35, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 1173, 5, -9, 0, 1000, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 1173, -4, 1, 0, 1000, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 1173, 2, 1, 0, 1000, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 1173, 2, 0, 0, 1000, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1173, 1, 1, 0, 1000, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1173, 4, 1, 0, 1000, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1173, -2, -2, 0, 35, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1173, -1, -9, 0, 1000, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1173, -1, -7, 0, 35, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1173, -1, 0, 0, 1000, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 1173, -1, 1, 0, 1000, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 1173, 0, 0, 0, 1000, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1173, 0, 1, 0, 1000, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 1173, -2, 1, 0, 1000, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 1173, -2, 0, 0, 1000, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 1173, -4, 0, 0, 1000, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 1173, -4, -9, 0, 1000, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 1173, -4, -8, 0, 1000, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 1173, -4, -7, 0, 1000, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 1173, -4, -6, 0, 1000, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 1173, -4, -5, 0, 1000, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1173, -4, -4, 0, 1000, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 1173, -1, 1, 0, 1000, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 1173, 1, 0, 0, 1000, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 1173, 5, 0, 0, 1000, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 1173, -4, -1, 0, 1000, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 1173, -3, -9, 0, 1000, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 1173, -2, -9, 0, 1000, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 1173, -2, -7, 0, 35, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 1173, -2, -5, 0, 35, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 1173, -2, -6, 0, 35, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 1173, -2, -4, 0, 35, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 1173, -2, -3, 0, 35, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 1173, 1, 1, 0, 1000, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 1173, 2, -4, 0, 35, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 1173, 2, -2, 0, 35, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 1173, 3, -9, 0, 1000, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 1173, 0, -2, 0, 35, -1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 1173, 1, -9, 0, 1000, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 1173, 1, -7, 0, 35, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 1173, -1, -2, 0, 35, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 1173, 0, -9, 0, 1000, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 1173, 0, -7, 0, 35, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1173, 0, 1, 0, 1000, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 1173, -2, 1, 0, 1000, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 1173, 3, 1, 0, 1000, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1173, 2, 1, 0, 1000, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 1173, -3, 0, 0, 1000, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 1173, -3, 1, 0, 1000, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 1173, -2, 4, 0, 5, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 1173, -4, 2, 0, 1000, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 1173, 0, 4, 0, 5, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 1173, 0, 5, 0, 5, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 1173, -1, 7, 0, 5, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 1173, -1, 6, 0, 5, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 1173, 4, 8, 0, 5, -1, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 1173, 4, 3, 0, 5, -1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 1173, 4, 4, 0, 5, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 1173, 1, 3, 0, 5, -1, "", 1);// 219
			AddComplexComponent( (BaseAddon) this, 1173, -4, 3, 0, 1000, -1, "", 1);// 230
			AddComplexComponent( (BaseAddon) this, 1173, -4, 4, 0, 1000, -1, "", 1);// 231
			AddComplexComponent( (BaseAddon) this, 1173, -4, 5, 0, 1000, -1, "", 1);// 232
			AddComplexComponent( (BaseAddon) this, 1173, -4, 7, 0, 1000, -1, "", 1);// 233
			AddComplexComponent( (BaseAddon) this, 1173, -4, 6, 0, 1000, -1, "", 1);// 234
			AddComplexComponent( (BaseAddon) this, 1173, -4, 8, 0, 1000, -1, "", 1);// 235
			AddComplexComponent( (BaseAddon) this, 1173, -4, 9, 0, 1000, -1, "", 1);// 236
			AddComplexComponent( (BaseAddon) this, 1173, -2, 8, 0, 5, -1, "", 1);// 241
			AddComplexComponent( (BaseAddon) this, 1173, 3, 3, 0, 5, -1, "", 1);// 251
			AddComplexComponent( (BaseAddon) this, 1173, 3, 8, 0, 5, -1, "", 1);// 255
			AddComplexComponent( (BaseAddon) this, 1173, 2, 8, 0, 5, -1, "", 1);// 257
			AddComplexComponent( (BaseAddon) this, 1173, 2, 5, 0, 5, -1, "", 1);// 259
			AddComplexComponent( (BaseAddon) this, 1173, 2, 3, 0, 5, -1, "", 1);// 262
			AddComplexComponent( (BaseAddon) this, 1173, 4, 3, 0, 5, -1, "", 1);// 273
			AddComplexComponent( (BaseAddon) this, 1173, 4, 4, 0, 5, -1, "", 1);// 274
			AddComplexComponent( (BaseAddon) this, 1173, 4, 5, 0, 5, -1, "", 1);// 275
			AddComplexComponent( (BaseAddon) this, 1173, 4, 6, 0, 5, -1, "", 1);// 276
			AddComplexComponent( (BaseAddon) this, 1173, -1, 3, 0, 5, -1, "", 1);// 281
			AddComplexComponent( (BaseAddon) this, 1173, -1, 8, 0, 5, -1, "", 1);// 286
			AddComplexComponent( (BaseAddon) this, 1173, 0, 3, 0, 5, -1, "", 1);// 291
			AddComplexComponent( (BaseAddon) this, 1173, 1, 4, 0, 5, -1, "", 1);// 292
			AddComplexComponent( (BaseAddon) this, 1173, 1, 5, 0, 5, -1, "", 1);// 293
			AddComplexComponent( (BaseAddon) this, 1173, 1, 8, 0, 5, -1, "", 1);// 294
			AddComplexComponent( (BaseAddon) this, 1173, 1, 6, 0, 5, -1, "", 1);// 295
			AddComplexComponent( (BaseAddon) this, 1173, 1, 7, 0, 5, -1, "", 1);// 296
			AddComplexComponent( (BaseAddon) this, 1173, -2, 3, 0, 5, -1, "", 1);// 307
			AddComplexComponent( (BaseAddon) this, 1173, 3, 3, 0, 5, -1, "", 1);// 310
			AddComplexComponent( (BaseAddon) this, 1173, 3, 4, 0, 5, -1, "", 1);// 311
			AddComplexComponent( (BaseAddon) this, 1173, 3, 5, 0, 5, -1, "", 1);// 312
			AddComplexComponent( (BaseAddon) this, 1173, 3, 6, 0, 5, -1, "", 1);// 313
			AddComplexComponent( (BaseAddon) this, 1173, 3, 8, 0, 5, -1, "", 1);// 314
			AddComplexComponent( (BaseAddon) this, 1173, 3, 7, 0, 5, -1, "", 1);// 315
			AddComplexComponent( (BaseAddon) this, 1173, 4, 5, 0, 5, -1, "", 1);// 320
			AddComplexComponent( (BaseAddon) this, 1173, 4, 6, 0, 5, -1, "", 1);// 321
			AddComplexComponent( (BaseAddon) this, 1173, 4, 7, 0, 5, -1, "", 1);// 322
			AddComplexComponent( (BaseAddon) this, 1173, -2, 4, 0, 5, -1, "", 1);// 326
			AddComplexComponent( (BaseAddon) this, 1173, -2, 6, 0, 5, -1, "", 1);// 327
			AddComplexComponent( (BaseAddon) this, 1173, -2, 5, 0, 5, -1, "", 1);// 328
			AddComplexComponent( (BaseAddon) this, 1173, -2, 7, 0, 5, -1, "", 1);// 329
			AddComplexComponent( (BaseAddon) this, 1173, -4, 8, 0, 1000, -1, "", 1);// 330
			AddComplexComponent( (BaseAddon) this, 1173, -4, 9, 0, 1000, -1, "", 1);// 331
			AddComplexComponent( (BaseAddon) this, 1173, 1, 6, 0, 5, -1, "", 1);// 335
			AddComplexComponent( (BaseAddon) this, 1173, 1, 8, 0, 5, -1, "", 1);// 337
			AddComplexComponent( (BaseAddon) this, 1173, -4, 2, 0, 1000, -1, "", 1);// 339
			AddComplexComponent( (BaseAddon) this, 1173, -4, 4, 0, 1000, -1, "", 1);// 340
			AddComplexComponent( (BaseAddon) this, 1173, -4, 5, 0, 1000, -1, "", 1);// 341
			AddComplexComponent( (BaseAddon) this, 1173, -4, 3, 0, 1000, -1, "", 1);// 342
			AddComplexComponent( (BaseAddon) this, 1173, -4, 6, 0, 1000, -1, "", 1);// 343
			AddComplexComponent( (BaseAddon) this, 1173, -4, 7, 0, 1000, -1, "", 1);// 344
			AddComplexComponent( (BaseAddon) this, 1173, -2, 5, 0, 5, -1, "", 1);// 352
			AddComplexComponent( (BaseAddon) this, 1173, -2, 6, 0, 5, -1, "", 1);// 353
			AddComplexComponent( (BaseAddon) this, 1173, -2, 7, 0, 5, -1, "", 1);// 354
			AddComplexComponent( (BaseAddon) this, 1173, -2, 8, 0, 5, -1, "", 1);// 356
			AddComplexComponent( (BaseAddon) this, 1173, 0, 8, 0, 5, -1, "", 1);// 361
			AddComplexComponent( (BaseAddon) this, 1173, 0, 6, 0, 5, -1, "", 1);// 391
			AddComplexComponent( (BaseAddon) this, 1173, 0, 7, 0, 5, -1, "", 1);// 392
			AddComplexComponent( (BaseAddon) this, 1173, 0, 8, 0, 5, -1, "", 1);// 393
			AddComplexComponent( (BaseAddon) this, 1173, 1, 3, 0, 5, -1, "", 1);// 398
			AddComplexComponent( (BaseAddon) this, 1173, -1, 5, 0, 5, -1, "", 1);// 399
			AddComplexComponent( (BaseAddon) this, 1173, -1, 4, 0, 5, -1, "", 1);// 400
			AddComplexComponent( (BaseAddon) this, 1173, -1, 3, 0, 5, -1, "", 1);// 402
			AddComplexComponent( (BaseAddon) this, 1173, 0, 3, 0, 5, -1, "", 1);// 403
			AddComplexComponent( (BaseAddon) this, 1173, -1, 8, 0, 5, -1, "", 1);// 404
			AddComplexComponent( (BaseAddon) this, 1173, 2, 5, 0, 5, -1, "", 1);// 411
			AddComplexComponent( (BaseAddon) this, 1173, 2, 6, 0, 5, -1, "", 1);// 412
			AddComplexComponent( (BaseAddon) this, 1173, 2, 7, 0, 5, -1, "", 1);// 413
			AddComplexComponent( (BaseAddon) this, 1173, 2, 8, 0, 5, -1, "", 1);// 415
			AddComplexComponent( (BaseAddon) this, 1173, 2, 4, 0, 5, -1, "", 1);// 418
			AddComplexComponent( (BaseAddon) this, 1173, 2, 3, 0, 5, -1, "", 1);// 419
			AddComplexComponent( (BaseAddon) this, 1173, 0, 5, 0, 5, -1, "", 1);// 420
			AddComplexComponent( (BaseAddon) this, 1173, 4, 7, 0, 5, -1, "", 1);// 421
			AddComplexComponent( (BaseAddon) this, 1173, 4, 8, 0, 5, -1, "", 1);// 422
			AddComplexComponent( (BaseAddon) this, 1173, -2, 3, 0, 5, -1, "", 1);// 427

		}

		public TvTArenaLobbyAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TvTArenaLobbyAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TvTArenaLobbyAddon();
			}
		}

		[Constructable]
		public TvTArenaLobbyAddonDeed()
		{
			Name = "TvTArenaLobby";
		}

		public TvTArenaLobbyAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}