/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////

namespace Server.Items
{
    public class FireplaceNewStoneWithBinAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FireplaceNewStoneWithBinAddonDeed();
			}
		}

		[ Constructable ]
		public FireplaceNewStoneWithBinAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 53 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 53 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 51 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 53 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 53 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 70 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 53 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 52 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 54 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1175;
			ac.Name = "fireplace";
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1175;
			ac.Name = "Hearth";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1175;
			ac.Name = "Hearth";
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1175;
			ac.Name = "Hearth";
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1175;
			ac.Name = "Hearth";
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1175;
			ac.Name = "Hearth";
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1175;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 82 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 83 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 84 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 84 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 84 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1180 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 7137 );
			AddComponent( ac, 0, 0, 2 );
			ac = new AddonComponent( 3561 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 0, 0, 5 );
			ac = new AddonComponent( 3561 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 0, 0, 4 );
			ac = new AddonComponent( 6572 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 0, 0, 6 );
			ac = new AddonComponent( 2557 );
			ac.Light = LightType.WestBig2;
			AddComponent( ac, 1, 2, 13 );
			ac = new AddonComponent( 2557 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 1, -1, 9 );
			ac = new AddonComponent( 52 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 52 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1251 );
			AddComponent( ac, 0, 3, 6 );
			ac = new AddonComponent( 84 );
			AddComponent( ac, 0, 0, 18 );
			ac = new AddonComponent( 84 );
			AddComponent( ac, 0, 1, 18 );
			ac = new AddonComponent( 73 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 65 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 67 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 7135 );
			AddComponent( ac, 0, 3, 6 );
			ac = new AddonComponent( 67 );
			AddComponent( ac, -1, 3, 5 );
			ac = new AddonComponent( 66 );
			AddComponent( ac, 0, 3, 6 );

		}

		public FireplaceNewStoneWithBinAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FireplaceNewStoneWithBinAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FireplaceNewStoneWithBinAddon();
			}
		}

		[Constructable]
		public FireplaceNewStoneWithBinAddonDeed()
		{
			Name = "Stone Fireplace & Bin";
		}

		public FireplaceNewStoneWithBinAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}