////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////

namespace Server.Items
{
    public class glassCoffeeTableEAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new glassCoffeeTableEAddonDeed();
			}
		}

		[ Constructable ]
		public glassCoffeeTableEAddon()
		{



			AddComplexComponent( (BaseAddon) this, 2819, 0, 1, 0, 0, -1, "table", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2821, 0, 0, 0, 0, -1, "table", 1);// 2
			AddComplexComponent( (BaseAddon) this, 7388, 0, 0, 4, 1150, -1, "frosted glass", 1);// 3
			AddComplexComponent( (BaseAddon) this, 7388, 0, 1, 4, 1150, -1, "frosted glass", 1);// 4

		}

		public glassCoffeeTableEAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class glassCoffeeTableEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new glassCoffeeTableEAddon();
			}
		}

		[Constructable]
		public glassCoffeeTableEAddonDeed()
		{
			Name = "glassCoffeeTableE";
		}

		public glassCoffeeTableEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}