////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////

namespace Server.Items
{
    public class pottedDaisiesWhiteSmallAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4556, 0, 0, 0}, {6094, 0, 0, 5}// 1	8	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new pottedDaisiesWhiteSmallAddonDeed();
			}
		}

		[ Constructable ]
		public pottedDaisiesWhiteSmallAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 4180, 0, 0, 7, 1150, -1, "daisies", 1);// 2
			AddComplexComponent( (BaseAddon) this, 4179, 0, 0, 0, 1150, -1, "daisies", 1);// 3
			AddComplexComponent( (BaseAddon) this, 4180, 0, 1, 8, 1150, -1, "daisies", 1);// 4
			AddComplexComponent( (BaseAddon) this, 4179, 1, 0, 8, 1150, -1, "daisies", 1);// 5
			AddComplexComponent( (BaseAddon) this, 4179, 0, 0, 4, 1150, -1, "daisies", 1);// 6
			AddComplexComponent( (BaseAddon) this, 6093, 0, 0, 5, 0, -1, "daisies", 1);// 7

		}

		public pottedDaisiesWhiteSmallAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class pottedDaisiesWhiteSmallAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new pottedDaisiesWhiteSmallAddon();
			}
		}

		[Constructable]
		public pottedDaisiesWhiteSmallAddonDeed()
		{
			Name = "pottedDaisiesWhiteSmall";
		}

		public pottedDaisiesWhiteSmallAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}