/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_FishingDockAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_FishingDockAddonDeed();
			}
		}

		[ Constructable ]
		public AG_FishingDockAddon()
		{
			AddComponent( new AddonComponent( 9307 ), 3, 4, 0 );
			AddComponent( new AddonComponent( 2172 ), -5, -1, 0 );
			AddComponent( new AddonComponent( 9301 ), -2, -3, 0 );
			AddComponent( new AddonComponent( 1997 ), -3, -1, 5 );
			AddComponent( new AddonComponent( 9308 ), -1, -2, 0 );
			AddComponent( new AddonComponent( 933 ), -1, -2, 0 );
			AddComponent( new AddonComponent( 1997 ), -1, -2, 5 );
			AddComponent( new AddonComponent( 940 ), -1, -2, 6 );
			AddComponent( new AddonComponent( 9308 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 1997 ), -1, -1, 5 );
			AddComponent( new AddonComponent( 937 ), -1, -1, 6 );
			AddComponent( new AddonComponent( 9308 ), 1, -2, 0 );
			AddComponent( new AddonComponent( 9308 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 9308 ), 2, -1, 0 );
			AddComponent( new AddonComponent( 9308 ), 2, -2, 0 );
			AddComponent( new AddonComponent( 9303 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 9303 ), 2, 0, 0 );
			AddComponent( new AddonComponent( 9308 ), 3, 2, 0 );
			AddComponent( new AddonComponent( 9306 ), 5, 4, 0 );
			AddComponent( new AddonComponent( 9308 ), 3, 0, 0 );
			AddComponent( new AddonComponent( 9308 ), 3, 1, 0 );
			AddComponent( new AddonComponent( 9308 ), 4, 2, 0 );
			AddComponent( new AddonComponent( 9308 ), 3, -2, 0 );
			AddComponent( new AddonComponent( 9308 ), 4, 0, 0 );
			AddComponent( new AddonComponent( 9305 ), 5, -2, 0 );
			AddComponent( new AddonComponent( 9305 ), 5, -1, 0 );
			AddComponent( new AddonComponent( 9305 ), 5, 2, 0 );
			AddComponent( new AddonComponent( 9305 ), 5, 0, 0 );
			AddComponent( new AddonComponent( 9307 ), -1, 4, 0 );
			AddComponent( new AddonComponent( 9309 ), -2, 4, 0 );
			AddComponent( new AddonComponent( 9308 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 9308 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 1997 ), -3, 2, 5 );
			AddComponent( new AddonComponent( 934 ), -3, 2, 6 );
			AddComponent( new AddonComponent( 933 ), -4, 2, 0 );
			AddComponent( new AddonComponent( 1997 ), -4, 2, 5 );
			AddComponent( new AddonComponent( 939 ), -4, 2, 6 );
			AddComponent( new AddonComponent( 1997 ), -4, 1, 5 );
			AddComponent( new AddonComponent( 938 ), -4, 1, 6 );
			AddComponent( new AddonComponent( 1997 ), -4, 0, 5 );
			AddComponent( new AddonComponent( 2172 ), -5, 0, 0 );
			AddComponent( new AddonComponent( 2172 ), -5, 1, 0 );
			AddComponent( new AddonComponent( 9308 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 1997 ), -1, 1, 5 );
			AddComponent( new AddonComponent( 937 ), -1, 1, 6 );
			AddComponent( new AddonComponent( 1997 ), -3, 0, 5 );
			AddComponent( new AddonComponent( 1997 ), -3, 1, 5 );
			AddComponent( new AddonComponent( 1997 ), -4, -1, 5 );
			AddComponent( new AddonComponent( 938 ), -4, -1, 6 );
			AddComponent( new AddonComponent( 9300 ), -1, -3, 0 );
			AddComponent( new AddonComponent( 9302 ), -2, -1, 0 );
			AddComponent( new AddonComponent( 1997 ), -2, -1, 5 );
			AddComponent( new AddonComponent( 9302 ), -2, -2, 0 );
			AddComponent( new AddonComponent( 1997 ), -2, -2, 5 );
			AddComponent( new AddonComponent( 936 ), -2, -2, 6 );
			AddComponent( new AddonComponent( 9304 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 9308 ), 0, -2, 0 );
			AddComponent( new AddonComponent( 9300 ), 0, -3, 0 );
			AddComponent( new AddonComponent( 9300 ), 1, -3, 0 );
			AddComponent( new AddonComponent( 9308 ), 1, 3, 0 );
			AddComponent( new AddonComponent( 9307 ), 0, 4, 0 );
			AddComponent( new AddonComponent( 9299 ), 5, -3, 0 );
			AddComponent( new AddonComponent( 1997 ), -3, -2, 5 );
			AddComponent( new AddonComponent( 936 ), -3, -2, 6 );
			AddComponent( new AddonComponent( 933 ), -4, -2, 0 );
			AddComponent( new AddonComponent( 1997 ), -4, -2, 5 );
			AddComponent( new AddonComponent( 941 ), -4, -2, 6 );
			AddComponent( new AddonComponent( 9307 ), 1, 4, 0 );
			AddComponent( new AddonComponent( 9308 ), 2, 3, 0 );
			AddComponent( new AddonComponent( 9300 ), 2, -3, 0 );
			AddComponent( new AddonComponent( 9300 ), 3, -3, 0 );
			AddComponent( new AddonComponent( 9307 ), 2, 4, 0 );
			AddComponent( new AddonComponent( 9303 ), 3, -1, 0 );
			AddComponent( new AddonComponent( 9300 ), 4, -3, 0 );
			AddComponent( new AddonComponent( 9308 ), 4, -1, 0 );
			AddComponent( new AddonComponent( 9308 ), 4, -2, 0 );
			AddComponent( new AddonComponent( 9307 ), 4, 4, 0 );
			AddComponent( new AddonComponent( 9304 ), 4, 3, 0 );
			AddComponent( new AddonComponent( 9305 ), 5, 3, 0 );
			AddComponent( new AddonComponent( 9308 ), 4, 1, 0 );
			AddComponent( new AddonComponent( 9305 ), 5, 1, 0 );
			AddComponent( new AddonComponent( 9308 ), 0, 3, 0 );
			AddComponent( new AddonComponent( 9303 ), 0, 2, 0 );
			AddComponent( new AddonComponent( 9308 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 9308 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 9302 ), -2, 1, 0 );
			AddComponent( new AddonComponent( 1997 ), -2, 1, 5 );
			AddComponent( new AddonComponent( 9302 ), -2, 0, 0 );
			AddComponent( new AddonComponent( 1997 ), -2, 0, 5 );
			AddComponent( new AddonComponent( 9308 ), -1, 2, 0 );
			AddComponent( new AddonComponent( 933 ), -1, 2, 0 );
			AddComponent( new AddonComponent( 1997 ), -1, 2, 5 );
			AddComponent( new AddonComponent( 938 ), -1, 2, 6 );
			AddComponent( new AddonComponent( 9308 ), -1, 3, 0 );
			AddComponent( new AddonComponent( 9308 ), 2, 2, 0 );
			AddComponent( new AddonComponent( 9308 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 1997 ), -1, 0, 5 );
			AddComponent( new AddonComponent( 937 ), -1, 0, 6 );
			AddComponent( new AddonComponent( 9304 ), 1, 2, 0 );
			AddComponent( new AddonComponent( 9302 ), -2, 3, 0 );
			AddComponent( new AddonComponent( 9302 ), -2, 2, 0 );
			AddComponent( new AddonComponent( 1997 ), -2, 2, 5 );
			AddComponent( new AddonComponent( 934 ), -2, 2, 6 );
			AddComponent( new AddonComponent( 9308 ), 3, 3, 0 );
			AddonComponent ac;
			ac = new AddonComponent( 9300 );
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 9300 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 9300 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 9300 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 9300 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 9301 );
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 9302 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 9302 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 9304 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 9303 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 933 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 933 );
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -4, -2, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -4, -1, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -3, -2, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -3, -1, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -2, -2, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -2, -1, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -1, -2, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -1, -1, 5 );
			ac = new AddonComponent( 940 );
			AddComponent( ac, -1, -2, 6 );
			ac = new AddonComponent( 941 );
			AddComponent( ac, -4, -2, 6 );
			ac = new AddonComponent( 936 );
			AddComponent( ac, -3, -2, 6 );
			ac = new AddonComponent( 936 );
			AddComponent( ac, -2, -2, 6 );
			ac = new AddonComponent( 937 );
			AddComponent( ac, -1, -1, 6 );
			ac = new AddonComponent( 2172 );
			AddComponent( ac, -5, -1, 0 );
			ac = new AddonComponent( 938 );
			AddComponent( ac, -4, -1, 6 );
			ac = new AddonComponent( 9302 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 9302 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 9302 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 9302 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 9309 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 9307 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 9307 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 9307 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 9307 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 9307 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 9304 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 9303 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 9303 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 9303 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 933 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 933 );
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -4, 0, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -4, 1, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -4, 2, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -3, 0, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -3, 1, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -3, 2, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -2, 0, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -2, 1, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -2, 2, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -1, 1, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -1, 2, 5 );
			ac = new AddonComponent( 939 );
			AddComponent( ac, -4, 2, 6 );
			ac = new AddonComponent( 938 );
			AddComponent( ac, -1, 2, 6 );
			ac = new AddonComponent( 937 );
			AddComponent( ac, -1, 0, 6 );
			ac = new AddonComponent( 937 );
			AddComponent( ac, -1, 1, 6 );
			ac = new AddonComponent( 934 );
			AddComponent( ac, -2, 2, 6 );
			ac = new AddonComponent( 934 );
			AddComponent( ac, -3, 2, 6 );
			ac = new AddonComponent( 2172 );
			AddComponent( ac, -5, 0, 0 );
			ac = new AddonComponent( 2172 );
			AddComponent( ac, -5, 1, 0 );
			ac = new AddonComponent( 938 );
			AddComponent( ac, -4, 1, 6 );
			ac = new AddonComponent( 9299 );
			AddComponent( ac, 5, -3, 0 );
			ac = new AddonComponent( 9300 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 9305 );
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 9305 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 9307 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 9306 );
			AddComponent( ac, 5, 4, 0 );
			ac = new AddonComponent( 9305 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 9305 );
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 9305 );
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 9305 );
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 9308 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 9304 );
			AddComponent( ac, 4, 3, 0 );

		}

		public AG_FishingDockAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_FishingDockAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_FishingDockAddon();
			}
		}

		[Constructable]
		public AG_FishingDockAddonDeed()
		{
			Name = "AG_FishingDock";
		}

		public AG_FishingDockAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}