/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class PoolSpaNew2WaterAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new PoolSpaNew2WaterAddonDeed();
			}
		}

		[ Constructable ]
		public PoolSpaNew2WaterAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1804 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 1802 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1810 );
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 1813 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 0, -2, 5 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1802 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 1804 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1293 );
			ac.Name = "water";
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1811 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 1812 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, -2, -1, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, -2, 0, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, -2, 1, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, -2, 2, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, -1, -1, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, -1, 1, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, -1, 2, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 0, -1, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 0, 0, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 0, 1, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 0, 2, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 1, -1, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 1, 1, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 1, 2, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 2, -1, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 2, 0, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 2, 1, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 2, 2, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 0, 3, 5 );
			ac = new AddonComponent( 2885 );
			AddComponent( ac, -3, 3, 5 );
			ac = new AddonComponent( 3237 );
			AddComponent( ac, -3, 3, 9 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 1803 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 1803 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 1805 );
			ac.Name = "water";
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1805 );
			ac.Name = "water";
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1811 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 1813 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 3, 0, 5 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1266;
			ac.Name = "water";
			AddComponent( ac, 3, 1, 5 );
			ac = new AddonComponent( 6420 );
			ac.Hue = 596;
			AddComponent( ac, 3, 3, 5 );
			ac = new AddonComponent( 6420 );
			ac.Hue = 476;
			AddComponent( ac, 3, 3, 7 );
			ac = new AddonComponent( 2519 );
			ac.Name = "candle holder";
			AddComponent( ac, 3, -1, 5 );
			ac = new AddonComponent( 5168 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 3, -1, 6 );

		}

		public PoolSpaNew2WaterAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class PoolSpaNew2WaterAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new PoolSpaNew2WaterAddon();
			}
		}

		[Constructable]
		public PoolSpaNew2WaterAddonDeed()
		{
			Name = "Pool & Spa";
		}

		public PoolSpaNew2WaterAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}